### ISSUE TITLE
KSVideoPlayerView (swiftui) and framerate matching

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#282]
Is it possible to add framerate matching and dynamic hdr on the tvOS swiftui demo app?  I've tried and failed.

**Comment by Alanko5** [comment]
Use options method:
‘preferredDisplayCriteria(….’

**Comment by cdg90** [comment]
> Use options method:
> ‘preferredDisplayCriteria(….’

Hello @Alanko5 , when I looked at “preferredDisplayCriteria” unfortunately I could not find any documentation.

https://developer.apple.com/documentation/avfoundation/avasset/2935636-preferreddisplaycriteria?language=swift

The idea is that AppleTVmatches 60, 50, 30, 25 and 24fps according to the stream (when needed) and to switch the video signal between SDR-HDR-Dolby vision. Is there a full template for this settings.

Like @UnknownCoder807  I do not know how to code those criteria in order to trigger the “Match Dynamic Range or Match Frame Rate”
I would really appreciate if you could help me on that matter

**Comment by cdg90** [comment]
> Use options method: ‘preferredDisplayCriteria(….’

@Alanko5 
I also found this:
https://qiita.com/hiroakit/items/43703bf275164fc2a849

If I apply it correctly to my code, can the content and FPS matching would work?

**Comment by Alanko5** [comment]
https://github.com/Alanko5/KSPlayer/blob/develop/Sources/KSPlayer/Video/tvOS/AVDisplayCriteriaKS.h

**Comment by Alanko5** [comment]
class `KSOptions`
have method
```
    open func preferredDisplayCriteria(refreshRate _: Float, videoDynamicRange _: Int32) -> AVDisplayCriteria? {
//        AVDisplayCriteria(refreshRate: fps, videoDynamicRange: dynamicRange.rawValue)
        nil
    }
```

if import this header:
```
https://github.com/Alanko5/KSPlayer/blob/develop/Sources/KSPlayer/Video/tvOS/AVDisplayCriteriaKS.h
```
then you use return value
`AVDisplayCriteria(refreshRate: fps, videoDynamicRange: dynamicRange.rawValue)`
