### ISSUE TITLE
Question: does spatial audio works automatically when available?

### ISSUE THREAD

**Issue by matteogobbi** [kingslay/KSPlayer#520]

**Comment by matteogobbi** [comment]
is it a yes? or do we need to set some `isUseAudioRenderer` to `true` manually only when necessary? If yes how do we discover when to set up `isUseAudioRenderer` to `true`?

**Comment by cdguy** [comment]
@matteogobbi you have to set a toggle (on/off) in your audio settings. Because when audio renderer (spatial audio) is enabled, the audio goes out of sync with the video, however I don’t know if the last commit has fixed this.
If the audio is stereo (2.0) the output sound won’t change, however, thanks to audio rendered enabled, the ios device and the airpods pro will create a software powered “fake” immersive 5.1 sound.

also, as I write to other developers who use ksplayer into their paid app for their commercial use, it would be great for @kingslay that you make a generous contribution :) knowing that your paid app iptvX is one of the most popular app that have a lot of subscribers :)

**Comment by matteogobbi** [comment]
Thanks!
My goal is also to try to help @kingslay to make the best player out there.

@kingslay please let us know your thoughts here. Thank you!

**Comment by kingslay** [comment]
@matteogobbi  用KSOptions.isSpatialAudioEnabled() 这个方法就可以判断设备是否支持Spatial。你可以通过这个方法来自动开启Spatial。因为目前Spatial的使用体验有点小问题。所以我默认是没有开启的。

**Comment by kingslay** [comment]
我这个项目开启了GitHub Sponsors。如果你觉得这个项目对你有用的话，那你可以用GitHub Sponsors来赞助这个项目

**Comment by cdguy** [comment]
> Thanks! My goal is also to try to help @kingslay to make the best player out there.
> 
> @kingslay please let us know your thoughts here. Thank you!

@matteogobbi
Yeah as I try to do also; for instance I am not on the list of the sponsors, however with @skrew and a few friends, we donated an appleTV to @kingslay when he informed us that he hasn’t one; since then, ksplayer has fixed a lot issues for the tvos build ;) you can do the same I am very confident about that 😊
