### ISSUE TITLE
A few Audio issues to be resolved

### ISSUE THREAD

**Issue by cdguy** [kingslay/KSPlayer#639]
We did a few audio tests with @JeremTM93 and we found some bugs:

1- If the default audio track has 7.1 properties; and we change to an audio that has 5.1 properties; the sound output is still 7.1. the audio output has to be 5.1 (video 1)

2- If the default audio track is DTS 7.1; Ksplayer outputs the sound as Stereo and as a result, the voices can't be heard (video2)

3- when an Atmos True HD audio track is selected, the sound quality is a bit deteriorated and Ksplayer does not output the sound in 7.1; the sound output remains in 5.1 (video 3)

I will share the video links via e-mail

https://collect.wetransfer.com/board/sskxcsi7wkgtt1zjf20231115080550/latest?token=87862bc6-88dd-4a00-8452-1fb96898b4a4

**Comment by kingslay** [comment]
@cdguy 是否可以麻烦你对这些视频截取出有问题的片段。然后上传到github。
这样我调试会更方便一点。因为你给的url我直接播放一般都会非常的卡顿（因为vpn的原因）所以我都要先截取下来，然后上传到NAS。这样我才能调试。如果你能帮我把前置工作做了。那可以提高这个bug解决的效率。如果视频片段不方便上传到github的话，那你可以直接通过邮件来发送。我理解几分钟的视频片段不会很大。
截取命令的示例
 ffmpeg -i http://xxx.com/123.mkv -map 0 -c copy -ss 00:00:50 -to 00:04:10  1.mkv

**Comment by kingslay** [comment]
还有你们用的audioPlayerType是什么呢？

**Comment by JeremTM93** [comment]
> 还有你们用的audioPlayerType是什么呢？

Hi, AudioUnit if that's what you're talking about.  I'll try to find an example with a lower bitrate.

But with AVAudioEngine it seems to me that it's the same, I'll look into it as soon as possible.

**Comment by kingslay** [comment]
@JeremTM93 我现在更新下testflight。 你等下用新的testflight试下。

**Comment by JeremTM93** [comment]
Thanks @kingslay

**Comment by kingslay** [comment]
这么大啊 那是否只要一分钟就可以重现这个问题了。你是否可以把视频在缩小为一分钟了 然后通过邮件或其他方式发给我

**Comment by cdguy** [comment]
> 这么大啊 那是否只要一分钟就可以重现这个问题了。你是否可以把视频在缩小为一分钟了 然后通过邮件或其他方式发给我

Please check the link below:

https://collect.wetransfer.com/board/sskxcsi7wkgtt1zjf20231115080550

"Video 1"- If the default audio track has 7.1 properties; and we change to an audio that has 5.1 properties; the sound output is still 7.1. the audio output has to be 5.1 

"Video 2"- If the default audio track is DTS 7.1; Ksplayer outputs the sound as Stereo and as a result, the voices can't be heard 

"Video 3"- when an Atmos True HD audio track is selected, the sound quality is a bit deteriorated and Ksplayer does not output the sound in 7.1; the sound output remains in 5.1 (video 3)

For "video1" ; please use the sample named "For Video1"
For "video2" and "video 3"; please use the sample named "For Video2and3"

**Comment by JeremTM93** [comment]
> @JeremTM93 我现在更新下testflight。 你等下用新的testflight试下。

No change with the new TestFlight

**Comment by chillout23** [comment]
I suggest also that KSPlayer **by default** selects the 5.1 channel as most people do not have 7.1 systems and there is usually problem with converting that down to 5.1. Right now if I playback a movie with 7.1 channels I do not get the proper audiotrack on rear surround speakers. It seems like I get the side surround as rear surround. Can you check that soundchannels are mapped to correct speakers @kingslay ? Could be difficult without actually having physical side-surround AND rear-surround channels.

**Comment by cdguy** [comment]
> I suggest also that KSPlayer **by default** selects the 5.1 channel soundtrack in the movie (sometimes both 7.1 and 5.1 is available) as most people do not have 7.1 systems and there is usually problem with converting that down to 5.1.
> 
> Also the 7.1 does not map correctly when having a 5.1 setup. Right now if I playback a movie with 7.1 channels I do not get the proper audiotrack on rear surround speakers. It seems like I get the side surround as rear surround. Can you check that soundchannels are mapped to correct speakers @kingslay ? Could be difficult without actually having physical side-surround AND rear-surround speakers.

1-Some audio channels not outputted correctly was mentioned just above in my comment
2- @JeremTM93 has one of the “most complete” sound setup with real speakers for each sound channel; he would definitely inform everyone if the mapping was wrong.
Also due to ffmpeg and apple restrictions, you can only get the atmos effects using the native player.

**Comment by chillout23** [comment]
@cdguy I understand that you cannot get Atmos with current FFMPEG and this is not about that. This is just my observations with 7.1 content as a 5.1 setup owner. @JeremTM93 with his 7.1 everything will sound fine because he has a setup for it. But with 5.1 setup (which I think most people have) this is the result.

**Comment by chillout23** [comment]
No matter what outcome of this topic, KSPlayer should select 5.1 as default and not prefer the 7.1 track to make it most compatible with most users. @kingslay

**Comment by JeremTM93** [comment]
@chillout23 
To be completely precise, my configuration is 5.1.2 also called 7.1 but without side speakers.  I don't think it's a player's role to choose a default track on the stream. The problem is elsewhere anyway, it's when we change sound tracks that KS has difficulty transcribing the right information.

When you play a film or an episode of a series that has a 5.1 track by default, do you have any problems with the sound ?
Isn't it when you change track that your problems appear ?
Could you be more specific ?

**Comment by chillout23** [comment]
Actually correcting myself, 5.1 only has SIDE surrounds not rear surrounds. 7.1 has the added REAR surrounds. I mix that up.

**Comment by JeremTM93** [comment]
@chillout23 
So there's nothing wrong with the default track, it's when you change the sound track that the problem arises, and that's the crux of the problem for you too, isn't it?

Personally, in my living room I have a Denon amplifier, with a centre speaker, a pair of 2+2 front speakers (Focal Sib Evo Atmos), a pair of rear speakers (Focal Sib Evo) and a subwoofer.

The configuration in my room is similar to yours, with an LG sp8ya 3+2 soundbar with subwoofer and 2 additional rear speakers, all in 5.1.2.

**Comment by chillout23** [comment]
@JeremTM93 No the default track works, the surround effects are just weird due to 7.1 and me having 5.1 setup.
For reference I am on the latest tvOS 17.2 beta. I have read people having issues with tvOS 17 in general when it comes to surround sound, so it's should be a good idea to verify the issues one may have only happens in KSPlayer and not other streaming apps, so we all do not troubleshoot something that is wrong already due to Apple's current OS version.

**Comment by chillout23** [comment]
I do not have any of these issues:

> 1- If the default audio track has 7.1 properties; and we change to an audio that has 5.1 properties; the sound output is still 7.1. the audio output has to be 5.1 (video 1)

2- If the default audio track is DTS 7.1; Ksplayer outputs the sound as Stereo and as a result, the voices can't be heard (video2)

3- when an Atmos True HD audio track is selected, the sound quality is a bit deteriorated and Ksplayer does not output the sound in 7.1; the sound output remains in 5.1 (video 3)

...but that may be because my system is 5.1 only.

The only thing I wanted to contribute to this thread was that @kingslay could add an option to make 5.1 default when opening a stream with multiple (5.1 and 7.1) options, and preferably also make it selectable in the code so App developers can default to 5.1 audio track for example. Maybe this is already done, I am not a Swift developer so no idea what to look for in the code.

**Comment by JeremTM93** [comment]
> @JeremTM93 No the default track works, the surround effects are just weird due to 7.1 and me having 5.1 setup.
> For reference I am on the latest tvOS 17.2 beta. I have read people having issues with tvOS 17 in general when it comes to surround sound, so it's should be a good idea to verify the issues one may have only happens in KSPlayer and not other streaming apps, so we all do not troubleshoot something that is wrong already due to Apple's current OS version.

As an ordinary user, I'm now avoiding all tvOS betas! I'm on 17.1.
But to answer your question, this is a KSPlayer problem, the Plex MPV fork doesn't have these problems when changing audio tracks during playback.

**Comment by kingslay** [comment]
> > @JeremTM93 我现在更新下testflight。 你等下用新的testflight试下。
> 
> No change with the new TestFlight

不好意思，我没有表达好意思。我的意思是AVAudioEngine 有点问题，需要我重新打包才进行AVAudioEngine的测试。这个问题还没修复。

**Comment by kingslay** [comment]
> Actually correcting myself, 5.1 only has SIDE surrounds not rear surrounds. 7.1 has the added REAR surrounds. I mix that up. Edited my above post.

@chillout23 5.1应该是环绕后置音响。7.1才增加了环绕侧音响。
![image](https://github.com/kingslay/KSPlayer/assets/3964055/b930340b-bc3e-49c0-ab51-b82a5074e2f9)

**Comment by kingslay** [comment]
当有外接音箱的话，这时候系统是无法准确的判断是音箱是5.1还是7.1。 我目前是会优先选择默认音轨，如果没有默认音轨的话，那会选择第一个音轨。在选择音轨这块是可以提供一个配置。让用户设置自己的音箱是5.1还是7.1。这样的话，就可以选择上对的音轨了。但是还有一件必须要做的事情，要支持7.1的音轨输出到5.1的设备上。因为电影里面可能只有7.1的音轨。但是这个音轨转化的话，有两个方式来实现：一个是ffmpeg来实现，一个是音响自己来实现（就是我给音响的是7.1，但是因为音响是5.1，需要音响自动的把7.1映射到5.1，我不知道是不是所有的音响都能很好的实现这个能力）。

**Comment by cdguy** [comment]
> 当有外接音箱的话，这时候系统是无法准确的判断是音箱是5.1还是7.1。 我目前是会优先选择默认音轨，如果没有默认音轨的话，那会选择第一个音轨。在选择音轨这块是可以提供一个配置。让用户设置自己的音箱是5.1还是7.1。这样的话，就可以选择上对的音轨了。但是还有一件必须要做的事情，要支持7.1的音轨输出到5.1的设备上。因为电影里面可能只有7.1的音轨。但是这个音轨转化的话，有两个方式来实现：一个是ffmpeg来实现，一个是音响自己来实现（就是我给音响的是7.1，但是因为音响是5.1，需要音响自动的把7.1映射到5.1，我不知道是不是所有的音响都能很好的实现这个能力）。

@JeremTM93 would also have a word about it, but I would suggest to use ffmpeg for handling the conversion because some (old) home theatres might not support down-mixing all audio codecs.

**Comment by chillout23** [comment]
> When there are external speakers, the system cannot accurately determine whether the speaker is 5.1 or 7.1. I currently give priority to the default audio track. If there is no default audio track, the first audio track will be selected. You can provide a configuration when selecting the audio track. Let users set whether their speakers are 5.1 or 7.1. This way, you can choose the right track. But there is one more thing that must be done, which is to support the output of 7.1 audio tracks to 5.1 devices. Because the movie may only have a 7.1 audio track. But there are two ways to convert this audio track: one is implemented by ffmpeg, and the other is implemented by the speaker itself (that is, the speaker I gave is 7.1, but because the speaker is 5.1, the speaker needs to automatically map 7.1 to 5.1 , I don’t know if all speakers can achieve this capability well).

Spot on @kingslay . The issue is that speakers cannot convert 7.1 to 5.1 if the speakers aren't receiving 7.1 signal due to TV not able to passthrough for example. So the most elegant option is to do this with ffmpeg, and also it would be convenient to let users set speaker mode (stereo, 5.1, or 7.1) in the app so the correct soundtrack can be selected.

**Comment by chillout23** [comment]
> > Actually correcting myself, 5.1 only has SIDE surrounds not rear surrounds. 7.1 has the added REAR surrounds. I mix that up. Edited my above post.
> 
> @chillout235.1 should be surround back speakers. 7.1 only adds surround side speakers. ![image](https://user-images.githubusercontent.com/3964055/283304786-b930340b-bc3e-49c0-ab51-b82a5074e2f9.png)

https://www.dolby.com/about/support/guide/surround-sound-speaker-setup/
Check the pictures on Dolby's website. 5.1 has side surrounds, but they can also be placed a little more to the back side of a main listening position. 7.1 adds rear surrounds.

**Comment by JeremTM93** [comment]
> > 当有外接音箱的话，这时候系统是无法准确的判断是音箱是5.1还是7.1。 我目前是会优先选择默认音轨，如果没有默认音轨的话，那会选择第一个音轨。在选择音轨这块是可以提供一个配置。让用户设置自己的音箱是5.1还是7.1。这样的话，就可以选择上对的音轨了。但是还有一件必须要做的事情，要支持7.1的音轨输出到5.1的设备上。因为电影里面可能只有7.1的音轨。但是这个音轨转化的话，有两个方式来实现：一个是ffmpeg来实现，一个是音响自己来实现（就是我给音响的是7.1，但是因为音响是5.1，需要音响自动的把7.1映射到5.1，我不知道是不是所有的音响都能很好的实现这个能力）。
> 
> @JeremTM93 would also have a word about it, but I would suggest to use ffmpeg for handling the conversion because some (old) home theatres might not support down-mixing all audio codecs.

I don't know how a player manages to adapt to the track selected and the user's equipment. The important thing is that it sends the right information and then it's up to the user's audio receiver to manage to reproduce the sound correctly ?

By the way @chillout23 how does a 7.1 track sound on your 5.1 installation with MPV ?

**Comment by chillout23** [comment]
> > > 当有外接音箱的话，这时候系统是无法准确的判断是音箱是5.1还是7.1。 我目前是会优先选择默认音轨，如果没有默认音轨的话，那会选择第一个音轨。在选择音轨这块是可以提供一个配置。让用户设置自己的音箱是5.1还是7.1。这样的话，就可以选择上对的音轨了。但是还有一件必须要做的事情，要支持7.1的音轨输出到5.1的设备上。因为电影里面可能只有7.1的音轨。但是这个音轨转化的话，有两个方式来实现：一个是ffmpeg来实现，一个是音响自己来实现（就是我给音响的是7.1，但是因为音响是5.1，需要音响自动的把7.1映射到5.1，我不知道是不是所有的音响都能很好的实现这个能力）。
> > 
> > 
> > @JeremTM93 would also have a word about it, but I would suggest to use ffmpeg for handling the conversion because some (old) home theatres might not support down-mixing all audio codecs.
> 
> I don't know how a player manages to adapt to the track selected and the user's equipment. The important thing is that it sends the right information and then it's up to the user's audio receiver to manage to reproduce the sound correctly ?
> 
> By the way @chillout23 how does a 7.1 track sound on your 5.1 installation with MPV ?

Don't have any proper app for MPV. Let me know how to test this.

**Comment by kingslay** [comment]
> surrounds
@chillout23  感觉他们的pdf里面的写法不一致。如果是只看图片的话。那7.1比 5.1 多了侧环绕音箱
https://www.dolby.com/siteassets/about/support/guide/setup-guides/5.1-virtual-speakers-setup/5_1_virtual_speaker_setup.pdf
![image](https://github.com/kingslay/KSPlayer/assets/3964055/7952cb6d-9f53-4180-a84d-dc12071d3c55)
https://www.dolby.com/siteassets/about/support/guide/setup-guides/7.1-virtual-speakers-setup/7_1_virtual_speaker_setup.pdf
![image](https://github.com/kingslay/KSPlayer/assets/3964055/2838115d-3f5d-4bec-aea8-a0cdf07c3456)

**Comment by chillout23** [comment]
@kingslay yes that is true, anyways, it does not matter much as people tend to place their surrounds as they like, some more to the side, some more to the rear. :)

**Comment by JeremTM93** [comment]
@chillout23 have you only tested your installation with KSPlayer ??
In other words, do you have any problems rendering a 7.1 track on your 5.1 installation than with KSPlayer ?

**Comment by chillout23** [comment]
> @chillout23 have you only tested your installation with KSPlayer ?? In other words, do you have any problems rendering a 7.1 track on your 5.1 installation than with KSPlayer ?

I have not tested any other app for 7.1, no. Just KSPlayer - and I'm reporting my findings here. The only issue I have right now is the 7.1 track not being mapped correctly, some effects are lost on the rear speakers. With 5.1 track selected I get all effects.

**Comment by JeremTM93** [comment]
> > @chillout23 have you only tested your installation with KSPlayer ?? In other words, do you have any problems rendering a 7.1 track on your 5.1 installation than with KSPlayer ?
> 
> I have not tested any other app for 7.1, no. Just KSPlayer - and I'm reporting my findings here. The only issue I have right now is the 7.1 track not being mapped correctly, some effects are lost on the rear speakers. With 5.1 track selected I get all effects.

Why didn't you test it with another player already?
We know that KSPlayer doesn't give the right information when there's a change of soundtrack, but for me it does a good job on the default track, even on a 7.1 track, I'll explain...

I'm playing a 7.1 track (TrueHD+ Atmos) :

![1000007148.jpg](https://github.com/kingslay/KSPlayer/assets/121438307/13aac523-e18f-4a5b-89d9-2fdde433f57f)

My amp receives 7.1 well (the 7.1 track is the default on this film) :

![1000007146.jpg](https://github.com/kingslay/KSPlayer/assets/121438307/4dc750f0-4adf-4ebe-8b43-bb5bde179e54)

But it only processes what it can, ignoring Atmos channels because of LPCM and direct mode :

![1000007147.jpg](https://github.com/kingslay/KSPlayer/assets/121438307/304e0a4f-e4fb-45d7-a6f3-0eef731e99a3)

However, if I use a DSP that enriches the sound, such as "Neural X" or "Dolby Surround", my Atmos speakers will be activated with a more or less convincing result (depending on the quality of the equipment) :

![1000007149.jpg](https://github.com/kingslay/KSPlayer/assets/121438307/5ed10e38-5f95-4b43-954a-b8d225cdaba5)

But in any case, KSPlayer on the default track doesn't present any sound reproduction problems (Except for a particular codec, dts 7.1, detailed above.)
I find it curious that there hasn't been any other feedback like yours here, too.

You should therefore try with another player to determine whether it's not your sound system that's the problem, I'm afraid you're confusing the developer for nothing.
Also try activating the pure or direct mode on your installation, it could be your DSP that's messing things up.

**Comment by chillout23** [comment]
I'll try Lilly Player with MPV config to see if there is any difference. I don't have an AV-receiver like you. I am giving my opinion from a soundbar perspective with TV passthrough, it's a bit different. You can see more details about stuff. How does your soundbar-setup work for you (which is more similar to my setup)?

**Comment by kingslay** [comment]
@JeremTM93 我尝试修复了下这个问题。第二个问题解决了。麻烦你看下第一个问题，和第三个问题是否还会存在。等下testflight就会更新了。

**Comment by chillout23** [comment]
Ok, if it works for you guys then all is good. You have proper equipment for this so I trust your tests.

**Comment by JeremTM93** [comment]
> Ok, if it works for you guys then all is good. You have proper equipment for this so I trust your tests.

Do you have a Telegram profile ? We could chat more easily and explore leads if you don't mind.

**Comment by chillout23** [comment]
> > Ok, if it works for you guys then all is good. You have proper equipment for this so I trust your tests.
> 
> Do you have a Telegram profile ? We could chat more easily and explore leads if you don't mind.

I only have Discord, unfortunately. If you have let me know and I can add you.

**Comment by cdguy** [comment]
all 3 issues are fixed!!!!
also confirmed by @JeremTM93 

Thank you @kingslay

**Comment by JeremTM93** [comment]
A huge thank you @kingslay, really great work 👌

@cdguy thank you for being so valuable in sending the pieces to the developer 🙏

**Comment by cdguy** [comment]
great team work! @kingslay @JeremTM93

**Comment by edge261** [comment]
Just to confirm... Atmos tracks won't play as Atmos (with height channels) but as 5.1 or 7.1, right? Or how do I have to configure TracyPlayer to get Atmos output?

**Comment by cdguy** [comment]
> Just to confirm... Atmos tracks won't play as Atmos (with height channels) but as 5.1 or 7.1, right? Or how do I have to configure TracyPlayer to get Atmos output?

Only AVplayer supports Dolby Atmos, otherwise a licence fee has to be paid.
That’s how infuse can output Dolby Atmos
