### ISSUE TITLE
Issue with some live tv streams

### ISSUE THREAD

**Issue by UnknownCoder807** [kingslay/KSPlayer#701]
Lots of my users are mentioning freezes in their live tv streams.

The stream plays ok for around 20 seconds and then the video will freeze but the audio continues.  

These are the logs (they are truncated because they repeat hundreds of times)

I have a url that has this behaviour which I can send via email if you need.

```
warning KSPlayer: KSMEPlayer.swift:375 prepareToPlay() | prepareToPlay <KSPlayer.KSMEPlayer: 0x280a67840>
error KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | non-existing PPS 0 referenced
error KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | non-existing PPS 0 referenced
error KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | decode_slice_header error
error KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | no frame!
```

```
warning KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | Increasing reorder buffer to 2
warning KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | Increasing reorder buffer to 3
warning KSPlayer: KSOptions.swift:504 outputNumberOfChannels(channelCount:) | [audio] maximumOutputNumberOfChannels: 32, preferredOutputNumberOfChannels: 0, isSpatialAudioEnabled: false, isUseAudioRenderer: false
warning KSPlayer: KSOptions.swift:508 outputNumberOfChannels(channelCount:) | [audio] currentRoute max channels: 2
warning KSPlayer: KSOptions.swift:523 outputNumberOfChannels(channelCount:) | [audio] outputNumberOfChannels: 2 output channelCount: 2
warning KSPlayer: AVFFmpegExtension.swift:407 layoutTag | [audio] FFmepg AVChannelLayout: stereo order: AVChannelOrder(rawValue: 1) mask: 3
warning KSPlayer: Resample.swift:349 audioFormat(sampleFormat:sampleRate:outChannel:channelCount:) | [audio] out channelLayout: stereo
warning KSPlayer: KSMEPlayer.swift:201 sourceDidOpened() | [audio] audio type: KSPlayer.AudioEnginePlayer prepare audioFormat )
warning KSPlayer: AudioEnginePlayer.swift:166 prepare(audioFormat:) | [audio] set preferredOutputNumberOfChannels: 2
warning KSPlayer: AudioEnginePlayer.swift:168 prepare(audioFormat:) | [audio] outputFormat AudioFormat: <AVAudioFormat 0x289cfd680:  2 ch,  48000 Hz, Float32, deinterleaved>
warning KSPlayer: AudioEnginePlayer.swift:170 prepare(audioFormat:) | [audio] outputFormat channelLayout tag: 6619138, channelDescriptions: []
warning KSPlayer: AudioEnginePlayer.swift:185 prepare(audioFormat:) | [audio] new sourceNode inputFormat: <AVAudioFormat 0x28191e440:  2 ch,  48000 Hz, Float32, deinterleaved>
warning KSPlayer: KSPlayerLayer.swift:141 state | playerStateDidChange - readyToPlay
warning KSPlayer: KSMEPlayer.swift:382 play() | play <KSPlayer.KSMEPlayer: 0x280a67840>
warning KSPlayer: KSPlayerLayer.swift:141 state | playerStateDidChange - buffering
```

```
warning KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | vt decoder cb: output image buffer is null: -12909
error KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | hardware accelerator failed to decode picture
warning KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | vt decoder cb: output image buffer is null: -12909
error KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | hardware accelerator failed to decode picture
warning KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | vt decoder cb: output image buffer is null: -12909
error KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | hardware accelerator failed to decode picture
```

**Comment by kingslay** [comment]
麻烦你发给我对应的url

**Comment by kingslay** [comment]
我的网络播放你提供的url很卡，很久才能播放一小段。我播放了很久了。没有出现你说的音频在播放但是视频画面被冻结的情况。

**Comment by UnknownCoder807** [comment]
How long did you watch for?  I just tried and it took around 1 minute to happen.  I guess it's quicker when there is football on.

**Comment by kingslay** [comment]
嗯，我是在tvos上的，我看了有十多分钟了。但是我的网络播放你这个url很卡，播放几秒就会卡很久。所以可能是因为这个原因所以无法复现你的这个问题。你可以用我的testflight。试下会不会有这个问题。我刚更新了testflight

**Comment by cdguy** [comment]
> 嗯，我是在tvos上的，我看了有十多分钟了。但是我的网络播放你这个url很卡，播放几秒就会卡很久。所以可能是因为这个原因所以无法复现你的这个问题。你可以用我的testflight。试下会不会有这个问题。我刚更新了testflight

The stream plays fine when it is a recording. so it is not an encoding issue; it looks like it is more related to incoming data management.
Because it would be difficult to

> warning KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | vt decoder cb: output image buffer is null: -12909

@kingslay 

when I try to record the same stream using ffmpeg here is the error I get:

[h264 @ 00000280569b4000] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 00000280569b4000] decode_slice_header error
[h264 @ 00000280569b4000] no frame!
[h264 @ 00000280569b4000] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 00000280569b4000] decode_slice_header error
[h264 @ 00000280569b4000] no frame!
[h264 @ 00000280569b4000] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 00000280569b4000] decode_slice_header error
[h264 @ 00000280569b4000] no frame!
[h264 @ 00000280569b4000] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 00000280569b4000] decode_slice_header error
[h264 @ 00000280569b4000] no frame!
[h264 @ 00000280569b4000] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 00000280569b4000] decode_slice_header error
[h264 @ 00000280569b4000] no frame!
[h264 @ 00000280569b4000] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 00000280569b4000] decode_slice_header error
[h264 @ 00000280569b4000] no frame!
[h264 @ 00000280569b4000] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 00000280569b4000] decode_slice_header error
[h264 @ 00000280569b4000] no frame!
[h264 @ 00000280569b4000] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 00000280569b4000] decode_slice_header error
[h264 @ 00000280569b4000] no frame!
[h264 @ 00000280569b4000] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 00000280569b4000] decode_slice_header error
[h264 @ 00000280569b4000] no frame!
[h264 @ 00000280569b4000] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 00000280569b4000] decode_slice_header error
[h264 @ 00000280569b4000] no frame!
[h264 @ 00000280569b4000] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 00000280569b4000] decode_slice_header error
[h264 @ 00000280569b4000] no frame!
[h264 @ 00000280569b4000] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 00000280569b4000] decode_slice_header error
[h264 @ 00000280569b4000] no frame!
[h264 @ 00000280569b4000] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 00000280569b4000] decode_slice_header error
[h264 @ 00000280569b4000] no frame!
[h264 @ 00000280569b4000] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 00000280569b4000] decode_slice_header error
[h264 @ 00000280569b4000] no frame!
[h264 @ 00000280569b4000] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 00000280569b4000] decode_slice_header error
[h264 @ 00000280569b4000] no frame!
[h264 @ 00000280569b4000] non-existing SPS 0 referenced in buffering period
    Last message repeated 1 times
[h264 @ 00000280569b4000] Increasing reorder buffer to 2
[h264 @ 00000280569b4000] Increasing reorder buffer to 3


Besides, looking at this error code, it seems that time to time, Ksplayer can't download/process the following frames.


```
warning KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | vt decoder cb: output image buffer is null: -12909
error KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | hardware accelerator failed to decode picture
warning KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | vt decoder cb: output image buffer is null: -12909
error KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | hardware accelerator failed to decode picture
warning KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | vt decoder cb: output image buffer is null: -12909
error KSPlayer: MEPlayerItem.swift:131 MEPlayerItem | hardware accelerator failed to decode picture
```


In my humble opinion, the best way to encounter this issue is to use one of the best features of MPV, which is the following:

1. It would be great if the live stream player could have a feature to seek back to a previous part of the stream, and then resume watching the live stream by hitting the "fast forward button" (+10 circle).

2. MPV has a feature that allows it to download cached data from the server in advance so that there is no buffering freeze or playback malfunction. With this feature, you can watch the stream with only a 1-second delay from what the server is streaming.

**Comment by cdguy** [comment]
https://github.com/kingslay/KSPlayer/assets/123307657/546f940b-48e1-4cfd-912c-6970958ced74

@kingslay you can see in this video that I can seek back a live stream and when I hit seek forward, the maximum allowed is -1 second.

**Comment by cdguy** [comment]
@kingslay 

Some of the main buffer settings are:

- **--cache=<yes|no|auto>**: This option decides whether to use network cache settings or not. The default value is auto, which enables caching depending on the media source. You can also force caching on or off with yes or no values.

- **--cache-secs=<seconds>**: This option sets the maximum amount of data to cache in seconds of playback. The default value is 3600, which means one hour of playback. This option is still limited by the --demuxer-max-bytes option.

- **--demuxer-max-bytes=<bytes>**: This option sets the maximum cache size in bytes. The default value is [1](https://github.com/mpv-player/mpv/issues/634)50M, which means 150 megabytes. You can use suffixes like K, M, G, etc. to specify the size. For example, --demuxer-max-bytes=1G means one gigabyte.

- **--cache-pause=<yes|no>**: This option decides whether to pause playback when the cache is too low. The default value is yes, which means playback will pause until enough data is cached. You can disable this option with no value.

- **--cache-pause-initial=<yes|no>**: This option decides whether to pause playback initially until the cache is filled up to --cache-pause-wait seconds. The default value is no, which means playback will start immediately. You can enable this option with yes value.

- **--cache-pause-wait=<seconds>**: This option sets the minimum amount of data to cache in seconds of playback before resuming playback after pausing. The default value is 1, which means one second of playback. This option is only effective if --cache-pause is enabled.

Something like the screenshot below can be made

![WhatsApp Görsel 2023-12-25 saat 15 33 30_1acc551c](https://github.com/kingslay/KSPlayer/assets/123307657/4095dc74-d255-4d7d-863e-68c131942514)

**Comment by cdguy** [comment]
@kingslay when I try to record the stream using ffmpeg, I noticed that the "downloaded time" is not updated as it should. a package of 10 seconds is downloaded every 10 seconds.
![Ekran görüntüsü 2023-12-27 164826](https://github.com/kingslay/KSPlayer/assets/123307657/374a648e-3cb3-43f7-91e4-1dedb5d71308)

**Comment by kingslay** [comment]
这两个流都是ts格式的吗？

**Comment by cdguy** [comment]
> 这两个流都是ts格式的吗？

yes they are

**Comment by cdguy** [comment]
@kingslay awesome work! Thank you. Fixed.

**Comment by kingslay** [comment]
@UnknownCoder807 你试下 看还会不会有问题 如果没有问题的话 那你就把这个问题关了

**Comment by UnknownCoder807** [comment]
Seems to be fixed, thanks @kingslay
