### ISSUE TITLE
HLG Support?

### ISSUE THREAD

**Issue by d3vilsown** [kingslay/KSPlayer#819]
Hey Guys, i'm using SnappierIPTV with KSPlayer for LiveTV on my Apple TV 4K 2022 tvOS 18.0. When i watch 4K Channels with HLG the TV instead triggers Dolby Vision and the Picture is very dark - is there a reason why they don't show up in HLG because the device should support it? If i try the same channels on my internal TV App they run perfectly fine in 4K HLG.
Thanks

**Comment by Kimentanm** [comment]
Yes, HLG is currently recognized as Dolby Vision @kingslay

**Comment by d3vilsown** [comment]
Hey, thanks for your reply - here's a sample. 
https://mega.nz/file/MgQE3AJR#CxNaXvjB8L-iiXFjLaIfgQIm3KvwSqHwFPzDFle3AtM

**Comment by UnknownCoder807** [comment]
> Thanks for the fast feedback, i've downloaded tracyplayer and it seems to work on my iphone 15 pro max. i'm on a business-trip rn, but will test it next weekend on my apple tv. maybe it's just a bad implementation of KSPlayer by Snappier IPTV. I'll get back to you asap.

There is no bad implementation on Snappier.  It's the latest KSPlayer LGPL branch, same as Tracyplayer.

If it works on tracyplayer, then it should work on other apps.

**Comment by cdguy** [comment]
> Yes, HLG is currently recognized as Dolby Vision @kingslay

Hello @Kimentanm last year I had a conversation with Kintan regarding HLG streams displayed as HDR10, because of the bit depth value.

normally HLG streams are not supposed to be in 10 bits as it should only be used for HDR10 live streams

https://github.com/kingslay/KSPlayer/issues/685#issuecomment-1845331037

I think it is related.

**Comment by Kimentanm** [comment]
App显示的参数是HLG，但是电视机（不是AppleTV）识别（点亮）出来的是杜比 @kingslay

**Comment by edge261** [comment]
Apple's HLG implementation outputs HLG as HDR10.

https://forums.developer.apple.com/forums/thread/666586
https://community.firecore.com/t/support-for-hdr-hlg/46169/13

It's weird, but it is what it is. For some reason, some apps output HLG as Dolby Vision to the TV, and I also believe is down to the KSPlayer engine and not the apps... would be good to check on that, because sometimes the devs just update the engine and that causes to trigger the DV.

**Comment by benykatz1** [comment]
@d3vilsown - what is your IPTV provider? I'll check it out. (seems it's high bitrate)
